### ISSUE TITLE
S3 presigned url gives 403 error

### ISSUE THREAD

**Issue by anders33** [spulec/moto#1170]
When trying to access data with a pre-signed, a 403 is returned.
Setting ACL='public-read' on the object give 200, when accessing the data.
Related to issue  #1125 

```
@mock_s3
def test_s3_object_in_public_bucket():
    s3 = boto3.resource('s3')
    bucket = s3.Bucket('test-bucket')
    bucket.create()
    bucket.put_object(Body=b'ABCD', Key='file.txt')
    params = {'Bucket': 'test-bucket','Key': 'file.txt'}
    presigned_url = boto3.client('s3').generate_presigned_url('get_object', params, ExpiresIn=900)
    response = requests.get(presigned_url)
    assert response.status_code == 200
```

**Comment by JackDanger** [comment]
This is now fixed in Moto 1.1.12

**Comment by anders33** [comment]
Tried with Moto 1.1.12 and the problem still exists.
The presigned url can't be opened if the ACL is set to 'private'

**Comment by JackDanger** [comment]
Looking into it

**Comment by hjwp** [comment]
just trying to get presigned URLs to work over here and running into this:

```
<Error>
<Code>InvalidAccessKeyId</Code>
<Message>The AWS Access Key Id you provided does not exist in our records.</Message>
<AWSAccessKeyId>foobar_key</AWSAccessKeyId>
<RequestId>MX998MFRH00WCM17</RequestId><HostId>KvPKbs092+e24tbCIeZMyrZwC5KQUmt10oKOIFfnanJaWHjk2HMZREh/kbf3aoC5I7m3FKZzQPc=</HostId>
</Error>
```

any tips on where to debug?  what does moto expect to use as its AWS Access Key Id?

**Comment by hjwp** [comment]
hmmm does `moto` use `responses` under the hood?  could there be some kind of interaction, if i'm trying to use `responses` separately in my tests?  is there a guide for how to get the two to play nicely?

**Comment by hjwp** [comment]
can i check if it's some kind of interaction with `responses`?  can i inspect the `Response` object to see if it it came from moto or from real amazon somehow?

**Comment by bblommers** [comment]
Hi @hjwp, can you open a new issue for this with a reproducible test case? This is implemented, and `responses` should work just fine alongside Moto - but it's difficult to tell what's wrong without a test case.

**Comment by hjwp** [comment]
thanks for taking the time to answer 😊

i doubt i can provide a minimal repro!  i'll try, sure.  but i think it's probably to do with some sort of conflict between local environment variables, the way i'm initializing boto clients, my config for responses in other tests... that's why i was asking for suggestions on how to debug, rather than just raising a new issue...

does moto use a specific default access key id?  is `foobar_key`?  does that error make you suspect that it's coming from a real s3 instance rather than moto maybe?

**Comment by bblommers** [comment]
`foobar_key` is the default access key that is set as an environment variable the moment `mock_s3` is initialized. 
Moto doesn't do any authentication unless specifically instructed to - that's why the response is most likely to come from a real S3 instance.

If you are able to hook up a debugger to the test case, the best place for a breakpoint in Moto would probably be here: https://github.com/spulec/moto/blob/8f79edba38430e8750c0c769f1b966cbeee9fd76/moto/core/models.py#L238
That would be invoked for every request to a URL mocked by Moto - i.e., would not be triggered by any of your own responses code.

Which Moto version are you on?
