### ISSUE TITLE
Importing mock_rds2 throws AttributeError starting in release 1.3.2

### ISSUE THREAD

**Issue by tjboring** [spulec/moto#1605]
I'm trying to use Moto for testing some RDS-related code, but it seems that something breaks between release 1.3.1 and 1.3.2.

Using both the `1.3.2` and `1.3.3` release, I'm experiencing this behavior (the traceback is the same in both versions, with just the `__version__` being different):

```
$ pip install moto==1.3.2
$ ipython
Python 3.6.1 (default, Apr  4 2017, 09:40:51)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from moto import mock_rds2
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-c2506f1e33cd> in <module>()
----> 1 from moto import mock_rds2

~/.virtualenvs/k8s_tools/lib/python3.6/site-packages/moto/__init__.py in <module>()
      6 __version__ = '1.3.2'
      7
----> 8 from .acm import mock_acm  # flake8: noqa
      9 from .apigateway import mock_apigateway, mock_apigateway_deprecated  # flake8: noqa
     10 from .autoscaling import mock_autoscaling, mock_autoscaling_deprecated  # flake8: noqa

~/.virtualenvs/k8s_tools/lib/python3.6/site-packages/moto/acm/__init__.py in <module>()
      1 from __future__ import unicode_literals
----> 2 from .models import acm_backends
      3 from ..core.models import base_decorator
      4
      5 acm_backend = acm_backends['us-east-1']

~/.virtualenvs/k8s_tools/lib/python3.6/site-packages/moto/acm/models.py in <module>()
      4 import json
      5 import datetime
----> 6 from moto.core import BaseBackend, BaseModel
      7 from moto.ec2 import ec2_backends
      8

~/.virtualenvs/k8s_tools/lib/python3.6/site-packages/moto/core/__init__.py in <module>()
      1 from __future__ import unicode_literals
----> 2 from .models import BaseModel, BaseBackend, moto_api_backend  # flake8: noqa
      3
      4 moto_api_backends = {"global": moto_api_backend}

~/.virtualenvs/k8s_tools/lib/python3.6/site-packages/moto/core/models.py in <module>()
    125
    126
--> 127 class CallbackResponse(responses.CallbackResponse):
    128     '''
    129     Need to subclass so we can change a couple things

AttributeError: module 'responses' has no attribute 'CallbackResponse'
```

Installing `1.3.1` works fine, though:
```
$ pip install moto==1.3.1
Python 3.6.1 (default, Apr  4 2017, 09:40:51)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from moto import mock_rds2

In [2]:
```

I tried poking around the PRs in the `1.3.1` and `1.3.2` releases, but the only thing I can see that is related is this commit:
https://github.com/spulec/moto/commit/cd1c6d3e6c3c80bf55fbfd6a657ba642c6fb4e3f

which introduces the `CallbackResponse` class, which is supposed to be a subclass of `responses.CallbackResponse`. But I haven't dug deep enough to go much beyond this point.

For now, I can just use the `1.3.1` release, but I'd be interested to know if there is something else I'm overlooking for why `1.3.3` is throwing that `AttributeError`.

```
# botocore version
$ pip list|grep botocore
botocore (1.10.11)
```

**Comment by spulec** [comment]
Thanks for opening. This should be fixed with https://github.com/spulec/moto/commit/b5bdf6693c1ed615571b1099766c411600d3db10

**Comment by NelsonScott** [comment]
@spulec this still happens for me when trying to use 1.3.3

```
root@a79c5036db89:/var/peloton/api# pip install moto==1.3.3
Collecting moto==1.3.3
  Using cached https://files.pythonhosted.org/packages/b3/a8/fccbacf94fdaa474316c4f65289d58b0271d1352e35628014bc071aa7291/moto-1.3.3-py2.py3-none-any.whl
Requirement already satisfied: jsondiff==1.1.1 in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: werkzeug in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: boto>=2.36.0 in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: pyaml in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: Jinja2>=2.7.3 in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: xmltodict in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: responses in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: boto3>=1.6.16 in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: python-dateutil<2.7.0,>=2.1 in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: backports.tempfile; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: botocore>=1.9.16 in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: docker>=2.5.1 in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: mock in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: cryptography>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: cookies in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: six>1.9 in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: requests>=2.5 in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: aws-xray-sdk<0.96,>=0.93 in /usr/local/lib/python2.7/dist-packages (from moto==1.3.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python2.7/dist-packages (from pyaml->moto==1.3.3)
Requirement already satisfied: MarkupSafe in /usr/local/lib/python2.7/dist-packages (from Jinja2>=2.7.3->moto==1.3.3)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /usr/local/lib/python2.7/dist-packages (from boto3>=1.6.16->moto==1.3.3)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python2.7/dist-packages (from boto3>=1.6.16->moto==1.3.3)
Requirement already satisfied: backports.weakref in /usr/local/lib/python2.7/dist-packages (from backports.tempfile; python_version < "3.3"->moto==1.3.3)
Requirement already satisfied: docutils>=0.10 in /usr/local/lib/python2.7/dist-packages (from botocore>=1.9.16->moto==1.3.3)
Requirement already satisfied: docker-pycreds>=0.3.0 in /usr/local/lib/python2.7/dist-packages (from docker>=2.5.1->moto==1.3.3)
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from docker>=2.5.1->moto==1.3.3)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from docker>=2.5.1->moto==1.3.3)
Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python2.7/dist-packages (from docker>=2.5.1->moto==1.3.3)
Requirement already satisfied: pbr>=0.11 in /usr/local/lib/python2.7/dist-packages (from mock->moto==1.3.3)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from mock->moto==1.3.3)
Requirement already satisfied: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.0.0->moto==1.3.3)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.0.0->moto==1.3.3)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.0.0->moto==1.3.3)
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.0.0->moto==1.3.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.5->moto==1.3.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.5->moto==1.3.3)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.5->moto==1.3.3)
Requirement already satisfied: wrapt in /usr/local/lib/python2.7/dist-packages (from aws-xray-sdk<0.96,>=0.93->moto==1.3.3)
Requirement already satisfied: jsonpickle in /usr/local/lib/python2.7/dist-packages (from aws-xray-sdk<0.96,>=0.93->moto==1.3.3)
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from s3transfer<0.2.0,>=0.1.10->boto3>=1.6.16->moto==1.3.3)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi!=1.11.3,>=1.7->cryptography>=2.0.0->moto==1.3.3)
Installing collected packages: moto
Successfully installed moto-1.3.3
You are using pip version 9.0.3, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@a79c5036db89:/var/peloton/api# ipython
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from moto import mock_s3
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-4c6f3b32ea3e> in <module>()
----> 1 from moto import mock_s3

/usr/local/lib/python2.7/dist-packages/moto/__init__.py in <module>()
      6 __version__ = '1.3.3'
      7 
----> 8 from .acm import mock_acm  # flake8: noqa
      9 from .apigateway import mock_apigateway, mock_apigateway_deprecated  # flake8: noqa
     10 from .autoscaling import mock_autoscaling, mock_autoscaling_deprecated  # flake8: noqa

/usr/local/lib/python2.7/dist-packages/moto/acm/__init__.py in <module>()
      1 from __future__ import unicode_literals
----> 2 from .models import acm_backends
      3 from ..core.models import base_decorator
      4 
      5 acm_backend = acm_backends['us-east-1']

/usr/local/lib/python2.7/dist-packages/moto/acm/models.py in <module>()
      4 import json
      5 import datetime
----> 6 from moto.core import BaseBackend, BaseModel
      7 from moto.ec2 import ec2_backends
      8 

/usr/local/lib/python2.7/dist-packages/moto/core/__init__.py in <module>()
      1 from __future__ import unicode_literals
----> 2 from .models import BaseModel, BaseBackend, moto_api_backend  # flake8: noqa
      3 
      4 moto_api_backends = {"global": moto_api_backend}

/usr/local/lib/python2.7/dist-packages/moto/core/models.py in <module>()
    125 
    126 
--> 127 class CallbackResponse(responses.CallbackResponse):
    128     '''
    129     Need to subclass so we can change a couple things

AttributeError: 'module' object has no attribute 'CallbackResponse'
```

Any thoughts on what could be going on?

**Comment by spulec** [comment]
Do you have another package/module named `responses`?

**Comment by NelsonScott** [comment]
@spulec ah yes we do, just found in test pip requirements `responses==0.4.0`
