### ISSUE TITLE
Missing requirement?

### ISSUE THREAD

**Issue by tcmnal** [spulec/moto#5269]
Recently switched from moto 3.1.14 to 3.1.15.

Now when using the @mock_ssm decorator, I get a ModuleNotFoundError for openapi_spec_validator. Minimum code example :

```
from moto import mock_ssm

@mock_ssm
def test_ssm():
   client = boto3.client('ssm')
```

Traceback (most recent call last):
  File "<bug-script>", line 4, in <module>
    def test_ssm():
  File "...\lib\site-packages\moto\__init__.py", line 30, in f
    module = importlib.import_module(module_name, "moto")
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "...\lib\site-packages\moto\ssm\__init__.py", line 1, in <module>
    from .models import ssm_backends
  File "...\lib\site-packages\moto\ssm\models.py", line 10, in <module>
    from moto.ec2 import ec2_backends
  File "...\lib\site-packages\moto\ec2\__init__.py", line 1, in <module>
    from .models import ec2_backends
  File "...\lib\site-packages\moto\ec2\models\__init__.py", line 14, in <module>
    from .elastic_block_store import EBSBackend
  File "...\lib\site-packages\moto\ec2\models\elastic_block_store.py", line 2, in <module>
    from moto.kms import kms_backends
  File "...\lib\site-packages\moto\kms\__init__.py", line 1, in <module>
    from .models import kms_backends
  File "...\lib\site-packages\moto\kms\models.py", line 9, in <module>
    from moto.apigateway.exceptions import ValidationException
  File "C:\dev\python-venvs\testing-cfct\lib\site-packages\moto\apigateway\__init__.py", line 1, in <module>
    from .models import apigateway_backends
  File "...\lib\site-packages\moto\apigateway\models.py", line 9, in <module>
    from openapi_spec_validator import validate_spec
ModuleNotFoundError: No module named 'openapi_spec_validator'

**Comment by bblommers** [comment]
Hi @tcmnal, that should be fixed in 3.1.16 - can you confirm that the latest release no longer throws an error?

**Comment by tcmnal** [comment]
@bblommers Yes, 3.1.16 is no longer throwing that error. For some reason my build container this morning was pulling 3.1.15 as the latest. Thanks

**Comment by prosaicpudding** [comment]
I am still seeing this when I use @mock_apigateway in 3.1.18

```
@mock_apigateway
def test_example():
    pass
```

```
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_io_utils.py:65: in <module>
    def test_get_aws_api_key(aws_credentials):
.venv2/lib/python3.9/site-packages/moto/__init__.py:30: in f
    module = importlib.import_module(module_name, "moto")
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
.venv2/lib/python3.9/site-packages/moto/apigateway/__init__.py:1: in <module>
    from .models import apigateway_backends
.venv2/lib/python3.9/site-packages/moto/apigateway/models.py:9: in <module>
    from openapi_spec_validator import validate_spec
E   ModuleNotFoundError: No module named 'openapi_spec_validator'
```

**Comment by bblommers** [comment]
Are you specifying the correct services when installing Moto, @prosaicpudding?

I.e.: `pip install moto[apigateway]`

See http://docs.getmoto.org/en/latest/docs/getting_started.html
